version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Extensions.Configuration.Binder
    versions:
    - "> 3.1.0, < 3.2"
  - dependency-name: Microsoft.Extensions.Configuration.CommandLine
    versions:
    - "> 3.1.0, < 3.2"
  - dependency-name: Microsoft.Extensions.Configuration.EnvironmentVariables
    versions:
    - "> 3.1.0, < 3.2"
  - dependency-name: Microsoft.Extensions.Logging.Abstractions
    versions:
    - "> 3.1.0, < 3.2"
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Stateless
    versions:
    - 5.1.8
    - 5.10.0
    - 5.10.1
  - dependency-name: MinVer
    versions:
    - 2.4.0
