<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\shared.props" />
  <PropertyGroup>
    <Authors>Damian Hickey</Authors>
    <PackageProjectUrl>https://github.com/damianh/LittleForker</PackageProjectUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>process-supervision, child-process</PackageTags>
    <Description>A utility to assist with spawning child processes, monitor their lifecycle and co-operative shutdown.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/damianh/LittleForker</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <MinVerMinimumMajorMinor>3.0</MinVerMinimumMajorMinor>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="MinVer" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Stateless" Version="5.20.1" />
  </ItemGroup>

</Project>
