<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\shared.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\LittleForker.Tests\SelfTerminatingProcess\</OutputPath>
  </PropertyGroup>

</Project>
